# Site settings
url: "https://chilebit.net"
author: "BlinkTrade"
baseurl: "/FX-Exchange"
#url: "//localhost:4000"   # activate this to test on your localhost
deploy_version: "HEAD"

exchange: "chilebit"
exchange_logo: "chilebit"

default_country_code: "CL"
blinktrade_broker_id: 5 # 9 is the id for the demo backend. Don't change that if you don't understand what you doing.

#blinktrade_backend_api: "api.blinktrade.com"
blinktrade_backend_api: "api.testnet.blinktrade.com"
#blinktrade_backend_api: "localhost"
google_analytics_id: "UA-56565606-1"
zopim_key: "2SSNIzvxy8fBypKoZJ0pI43tUoNCv8os"



# Build settings
markdown: kramdown


languages: ["es", "en_US", "pt_BR"]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb", "deploy.sh", "build_javascript.sh" ]
source:      .
destination: ./_site
plugins:     ./_plugins
paginate:    5
paginate_path: "post/page:num"
permalink:     /post/:title/
